import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Resend } from 'resend';

export interface SalarySlipMailPayload {
  to: string;
  employeeName: string;
  employeeCode: string;
  monthLabel: string;
  grossSalary: string;
  totalDeductions: string;
  netSalary: string;
  pdfBuffer: Buffer;
  filename: string;
}

@Injectable()
export class MailService implements OnModuleInit {
  private readonly logger = new Logger(MailService.name);
  private resend: Resend | null = null;
  private readonly apiKey: string | undefined;
  private readonly fromAddress: string;

  constructor(private readonly configService: ConfigService) {
    this.apiKey = this.configService.get<string>('RESEND_API_KEY');
    const fromName = this.configService.get<string>('MAIL_FROM_NAME') ?? 'EMS Payroll';
    const fromEmail = this.configService.get<string>('MAIL_FROM_ADDRESS') ?? 'noreply@yourdomain.com';
    this.fromAddress = `${fromName} <${fromEmail}>`;
  }

  onModuleInit() {
    if (!this.apiKey) {
      this.logger.warn(
        '[MAIL] Not configured — RESEND_API_KEY missing in environment. Salary slip emails are DISABLED.',
      );
      return;
    }

    this.resend = new Resend(this.apiKey);
    this.logger.log(`[MAIL] Resend configured. From: ${this.fromAddress}`);
  }

  isEnabled(): boolean {
    return !!this.resend;
  }

  async sendSalarySlip(payload: SalarySlipMailPayload): Promise<void> {
    if (!this.resend) {
      this.logger.warn(`[MAIL] sendSalarySlip skipped — mail not enabled (to: ${payload.to})`);
      return;
    }

    this.logger.log(`[MAIL] Sending salary slip to ${payload.to} (${payload.employeeCode}) for ${payload.monthLabel}`);

    const { data, error } = await this.resend.emails.send({
      from: this.fromAddress,
      to: payload.to,
      subject: `Salary Slip — ${payload.monthLabel} | ${payload.employeeName}`,
      html: this.buildHtml(payload),
      attachments: [
        {
          filename: payload.filename,
          content: payload.pdfBuffer,
        },
      ],
    });

    if (error) {
      throw new Error(`Resend API error: ${error.message}`);
    }

    this.logger.log(`[MAIL] Email accepted by Resend — id: ${data?.id}`);
  }

  private buildHtml(payload: SalarySlipMailPayload): string {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Arial, sans-serif; color: #333; font-size: 14px; margin: 0; padding: 0; }
    .container { max-width: 560px; margin: 32px auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
    .header { background: #1d4ed8; padding: 24px 28px; color: #fff; }
    .header h1 { margin: 0; font-size: 18px; font-weight: 700; }
    .header p { margin: 4px 0 0; font-size: 13px; opacity: 0.85; }
    .body { padding: 24px 28px; }
    .greeting { font-size: 15px; margin-bottom: 16px; }
    .summary { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 16px 20px; margin: 16px 0; }
    .summary table { width: 100%; border-collapse: collapse; }
    .summary td { padding: 5px 0; font-size: 13px; }
    .summary td:last-child { text-align: right; font-weight: 600; }
    .summary .net td { color: #1d4ed8; font-size: 15px; border-top: 1px solid #e5e7eb; padding-top: 10px; margin-top: 6px; }
    .note { font-size: 12px; color: #6b7280; margin-top: 20px; }
    .footer { background: #f1f5f9; padding: 14px 28px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Salary Slip — ${payload.monthLabel}</h1>
      <p>Employee ID: ${payload.employeeCode}</p>
    </div>
    <div class="body">
      <p class="greeting">Dear <strong>${payload.employeeName}</strong>,</p>
      <p>Please find your salary slip for <strong>${payload.monthLabel}</strong> attached to this email.</p>

      <div class="summary">
        <table>
          <tr><td>Gross Salary</td><td>${payload.grossSalary}</td></tr>
          <tr><td>Total Deductions</td><td>${payload.totalDeductions}</td></tr>
          <tr class="net"><td><strong>Net Pay</strong></td><td><strong>${payload.netSalary}</strong></td></tr>
        </table>
      </div>

      <p class="note">The full salary slip with all deduction details is attached as a PDF. Please contact HR if you have any questions.</p>
    </div>
    <div class="footer">This is an automated email generated by the Employee Management System. Please do not reply.</div>
  </div>
</body>
</html>`.trim();
  }
}
