import { CreateEmployeeDto } from '../employees/dto/create-employee.dto';
import { EmployeeStatus } from '../employees/entities/employee.entity';

/** First demo employee — used to detect if seed already ran */
export const DEMO_MARKER_CODE = 'DEMO-001';

export const DEMO_PAYROLL_YEARS = [2025, 2026] as const;

export const DEMO_GP_FUND_YEARS = [2025, 2026] as const;

/** 12 dummy employees across departments and tax slabs (11 active, 1 inactive) */
export const DEMO_EMPLOYEES: CreateEmployeeDto[] = [
  {
    employeeCode: 'DEMO-001',
    firstName: 'Ahmed',
    lastName: 'Hassan',
    email: 'ahmed.hassan@demo.local',
    phone: '03001234501',
    department: 'Engineering',
    designation: 'Junior Developer',
    basicSalary: 42000,
    joinDate: '2023-03-15',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-002',
    firstName: 'Fatima',
    lastName: 'Khan',
    email: 'fatima.khan@demo.local',
    phone: '03001234502',
    department: 'Human Resources',
    designation: 'HR Officer',
    basicSalary: 55000,
    joinDate: '2022-07-01',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-003',
    firstName: 'Usman',
    lastName: 'Ali',
    email: 'usman.ali@demo.local',
    phone: '03001234503',
    department: 'Finance',
    designation: 'Accounts Assistant',
    basicSalary: 48000,
    joinDate: '2024-01-10',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-004',
    firstName: 'Ayesha',
    lastName: 'Malik',
    email: 'ayesha.malik@demo.local',
    phone: '03001234504',
    department: 'Engineering',
    designation: 'Software Engineer',
    basicSalary: 95000,
    joinDate: '2021-11-20',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-005',
    firstName: 'Bilal',
    lastName: 'Ahmed',
    email: 'bilal.ahmed@demo.local',
    phone: '03001234505',
    department: 'Operations',
    designation: 'Operations Manager',
    basicSalary: 125000,
    joinDate: '2020-05-08',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-006',
    firstName: 'Sana',
    lastName: 'Raza',
    email: 'sana.raza@demo.local',
    phone: '03001234506',
    department: 'Information Technology',
    designation: 'Senior Developer',
    basicSalary: 165000,
    joinDate: '2019-09-12',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-007',
    firstName: 'Hamza',
    lastName: 'Sheikh',
    email: 'hamza.sheikh@demo.local',
    phone: '03001234507',
    department: 'Finance',
    designation: 'Finance Manager',
    basicSalary: 210000,
    joinDate: '2018-02-28',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-008',
    firstName: 'Zainab',
    lastName: 'Iqbal',
    email: 'zainab.iqbal@demo.local',
    phone: '03001234508',
    department: 'Administration',
    designation: 'Admin Officer',
    basicSalary: 72000,
    joinDate: '2023-08-05',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-009',
    firstName: 'Imran',
    lastName: 'Butt',
    email: 'imran.butt@demo.local',
    phone: '03001234509',
    department: 'Engineering',
    designation: 'Tech Lead',
    basicSalary: 285000,
    joinDate: '2017-06-18',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-010',
    firstName: 'Hira',
    lastName: 'Saeed',
    email: 'hira.saeed@demo.local',
    phone: '03001234510',
    department: 'Human Resources',
    designation: 'HR Manager',
    basicSalary: 118000,
    joinDate: '2020-12-01',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-011',
    firstName: 'Kamran',
    lastName: 'Yousaf',
    email: 'kamran.yousaf@demo.local',
    phone: '03001234511',
    department: 'Operations',
    designation: 'Supervisor',
    basicSalary: 88000,
    joinDate: '2022-04-22',
    status: EmployeeStatus.ACTIVE,
  },
  {
    employeeCode: 'DEMO-012',
    firstName: 'Nadia',
    lastName: 'Farooq',
    email: 'nadia.farooq@demo.local',
    phone: '03001234512',
    department: 'Information Technology',
    designation: 'Former Analyst',
    basicSalary: 65000,
    joinDate: '2021-03-30',
    status: EmployeeStatus.INACTIVE,
  },
];
